# Generated by Django 4.0.1 on 2022-04-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=150)),
                ('senderEmail', models.CharField(max_length=150)),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
    ]
