# Generated by Django 4.0.1 on 2022-04-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='Message',
            new_name='message',
        ),
    ]
