# Generated by Django 4.0.1 on 2022-04-13 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0003_rename_message_contact_us_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickupDeliveryPersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
