# Generated by Django 4.0.1 on 2022-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0006_alter_pickup_pickuppersonnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='contactNumber',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='pickup',
            name='pickupRequestByUserName',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
