# Generated by Django 4.0.1 on 2022-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0007_pickup_contactnumber_pickup_pickuprequestbyusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='deliveryPersonAadharNo',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='pickup',
            name='deliveryPersonName',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='pickup',
            name='deliveryPersonPhNo',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
