# Generated by Django 4.0.1 on 2022-04-02 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='otherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('aadharNo', models.CharField(max_length=20)),
                ('drivingLicenseNo', models.CharField(default=False, max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('profilePic', models.ImageField(upload_to='pics')),
                ('rating', models.FloatField(default=0, editable=False)),
                ('status', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
